# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
podfile: Example/Podfile
osx_image: xcode12.5
before_install:
    - gem install cocoapods
    - gem install xcpretty --no-document --quiet
    - pod repo update
    - pod install --project-directory=Example
script:
    - set -o pipefail && xcodebuild test -workspace Example/GTProgressBar.xcworkspace -scheme GTProgressBar-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'  ONLY_ACTIVE_ARCH=NO | xcpretty -c
after_success:
    - sleep 10
